### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by tmpbeing** [pandark/42header.vim#1]
Readme should read :Fortytwoheader instead of :FortyTwoHeader (case issues).
Tested :FortyTwoHeader under neovim and it didn't work.

**Comment by tasinttttttt** [comment]
Same thing here.
had to edit `line 179` of `./plugin/42header.vim` [[link](https://github.com/pandark/42header.vim/blob/master/plugin/42header.vim)] and replace 
`command! Fortytwoheader call s:fortytwoheader ()`
with
`command! FortyTwoHeader call s:fortytwoheader ()`.
It works on vim.

**Comment by pandark** [comment]
I actually meant for it to be camel cased (…and then something went wrong 😄), so let's make it be `FortyTwoHeader` everywhere.
https://github.com/pandark/42header.vim/blob/master/plugin/42header.vim#L179 (code)
https://github.com/pandark/42header.vim/blob/master/doc/42header.txt#L20 (doc)

Thanks you both for the feedback. 🙂
