### ISSUE TITLE
No makefile default behaviour

### ISSUE THREAD

**Issue by tmpbeing** [pandark/42header.vim#2]
Default delimiters are used for makefile. Seems like an oversight.

Also the defaults comment delimiters should probably be ['#', '#', '*'] instead of C-style comments as those are much more widely used.

**Comment by pandark** [comment]
Okay, Makefiles are used quite often, let's add this… 🙂
https://github.com/pandark/42header.vim/blob/master/plugin/42header.vim#L59
https://github.com/pandark/42header.vim/blob/master/after/plugin/stdheader.vim#L54 (duplicated to work around the preinstalled plugin).

**Comment by pandark** [comment]
I'm not sure about the default delimiters… I'll think about it 🙂

**Comment by tmpbeing** [comment]
Thanks !
